name = "gestion-humana"
type = "webpack"
account_id = "" # Deberás completar esto con tu ID de cuenta de Cloudflare
route = ""
zone_id = "" # Deberás completar esto con tu Zone ID si tienes un dominio personalizado
usage_model = "bundled"
workers_dev = true

[site]
bucket = "./out"
entry-point = "workers-site"

[build]
command = "npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "18"