name = "gestion-humana"
type = "webpack"

[site]
single_page_app = true

[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "20.19.0"

[build.processing]
skip_missing = true

[build.processing.html]
ignore = [".next/*"]

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.static]
ignore = [".next/*"]

[cache]
paths = [".next/cache/**/*"]